### ISSUE TITLE
Creating a VM from a VM image fails with "In order to use extension reference, ProvisionGuestAgent must be set during virtual machine provisioning."

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-sdk-for-go#155]
From the integration tests:
```
github.com\Azure\azure-sdk-for-go\management\vmutils>go test -timeout 30m .
--- FAIL: TestDeployFromVmImage (39.22s)
        integration_test.go:208: Retrieving storage account
        managementclient.go:51: AZURE: GET services/storageservices
        managementclient.go:55:    <<< <StorageServices xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><StorageService><Url>https://management.core.windows.net/c33f5e65-247c-4819-8bcc-0cb2c3b354df/services/storageservices/pmtest1451430345676939</Url><ServiceName>pmtest1451430345676939</ServiceName><StorageServiceProperties><Description i:nil="true"/><Location>East US 2</Location><Label>cG10ZXN0MTQ1MTQzMDM0NTY3NjkzOQ==</Label><Status>Created</Status><Endpoints><Endpoint>https://pmtest1451430345676939.blob.core.windows.net/</Endpoint><Endpoint>https://pmtest1451430345676939.queue.core.windows.net/</Endpoint><Endpoint>https://pmtest1451430345676939.table.core.windows.net/</Endpoint></Endpoints><GeoPrimaryRegion>East US 2</GeoPrimaryRegion><StatusOfPrimary>Available</StatusOfPrimary><GeoSecondaryRegion/><StatusOfSecondary/><CreationTime>2015-04-29T22:14:38Z</CreationTime><CustomDomains/><AccountType>Standard_LRS</AccountType></StorageServiceProperties><ExtendedProperties><ExtendedProperty><Name>ResourceGroup</Name><Value>Default-Storage-EastUS2</Value></ExtendedProperty><ExtendedProperty><Name>ResourceLocation</Name><Value>East US 2</Value></ExtendedProperty></ExtendedProperties></StorageService><StorageService><Url>https://management.core.windows.net/c33f5e65-247c-4819-8bcc-0cb2c3b354df/services/storageservices/pmwus123</Url><ServiceName>pmwus123</ServiceName><StorageServiceProperties><Description i:nil="true"/><Location>West US</Location><Label>cG13dXMxMjM=</Label><Status>Created</Status><Endpoints><Endpoint>https://pmwus123.blob.core.windows.net/</Endpoint><Endpoint>https://pmwus123.queue.core.windows.net/</Endpoint><Endpoint>https://pmwus123.table.core.windows.net/</Endpoint></Endpoints><GeoPrimaryRegion>West US</GeoPrimaryRegion><StatusOfPrimary>Available</StatusOfPrimary><GeoSecondaryRegion>East US</GeoSecondaryRegion><StatusOfSecondary>Available</StatusOfSecondary><CreationTime>2015-04-02T21:58:38Z</CreationTime><CustomDomains/><AccountType>Standard_GRS</AccountType></StorageServiceProperties><ExtendedProperties><ExtendedProperty><Name>ResourceGroup</Name><Value>Default-Storage-WestUS</Value></ExtendedProperty><ExtendedProperty><Name>ResourceLocation</Name><Value>West US</Value></ExtendedProperty></ExtendedProperties></StorageService><StorageService><Url>https://management.core.windows.net/c33f5e65-247c-4819-8bcc-0cb2c3b354df/services/storageservices/portalvhdsw6j5mnbx6qmy</Url><ServiceName>portalvhdsw6j5mnbx6qmy</ServiceName><StorageServiceProperties><Description>Implicitly created storage service</Description><Location>South Central US</Location><Label>cG9ydGFsdmhkc3c2ajVtbmJ4NnFteQ==</Label><Status>Created</Status><Endpoints><Endpoint>https://portalvhdsw6j5mnbx6qmy.blob.core.windows.net/</Endpoint><Endpoint>https://portalvhdsw6j5mnbx6qmy.queue.core.windows.net/</Endpoint><Endpoint>https://portalvhdsw6j5mnbx6qmy.table.core.windows.net/</Endpoint></Endpoints><GeoPrimaryRegion>South Central US</GeoPrimaryRegion><StatusOfPrimary>Available</StatusOfPrimary><GeoSecondaryRegion>North Central US</GeoSecondaryRegion><StatusOfSecondary>Available</StatusOfSecondary><CreationTime>2015-04-13T22:44:53Z</CreationTime><CustomDomains/><AccountType>Standard_GRS</AccountType></StorageServiceProperties><ExtendedProperties><ExtendedProperty><Name>ResourceGroup</Name><Value>Default-Storage-SouthCentralUS</Value></ExtendedProperty><ExtendedProperty><Name>ResourceLocation</Name><Value>South Central US</Value></ExtendedProperty></ExtendedProperties></StorageService><StorageService><Url>https://management.core.windows.net/c33f5e65-247c-4819-8bcc-0cb2c3b354df/services/storageservices/sdkih3l426kgf5o</Url><ServiceName>sdkih3l426kgf5o</ServiceName><StorageServiceProperties><Description i:nil="true"/><Location>East Asia</Location><Label>c2RraWgzbDQyNmtnZjVv</Label><Status>Created</Status><Endpoints><Endpoint>https://sdkih3l426kgf5o.blob.core.windows.net/</Endpoint><Endpoint>https://sdkih3l426kgf5o.queue.core.windows.net/</Endpoint><Endpoint>https://sdkih3l426kgf5o.table.core.windows.net/</Endpoint></Endpoints><GeoPrimaryRegion>East Asia</GeoPrimaryRegion><StatusOfPrimary>Available</StatusOfPrimary><GeoSecondaryRegion/><StatusOfSecondary/><CreationTime>2015-03-26T17:04:52Z</CreationTime><CustomDomains/><AccountType>Standard_LRS</AccountType></StorageServiceProperties><ExtendedProperties><ExtendedProperty><Name>ResourceGroup</Name><Value>Default-Storage-EastAsia</Value></ExtendedProperty><ExtendedProperty><Name>ResourceLocation</Name><Value>East Asia</Value></ExtendedProperty></ExtendedProperties></StorageService></StorageServices>
        integration_test.go:246: Selected storage account 'portalvhdsw6j5mnbx6qmy' in location 'South Central US'
        integration_test.go:298: Selecting VM image
        managementclient.go:51: AZURE: GET services/vmimages
        managementclient.go:55:    <<< <VMImages xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><VMImage><Name>PackerMade_OpenLogicImage_2015-April-25_0-10</Name><Label>PackerMade_OpenLogicImage</Label><Category>User</Category><Description>paker made image</Description><OSDiskConfiguration><Name>PackerMade_OpenLogicImage_2015-April-25_0-10-os-2015-04-25</Name><HostCaching>ReadWrite</HostCaching><OSState>Generalized</OSState><OS>Linux</OS><MediaLink>https://pmwus123.blob.core.windows.net/images/PackerMade_OpenLogicImage_2015-April-25_0-10-os-2015-04-25.vhd</MediaLink><LogicalDiskSizeInGB>30</LogicalDiskSizeInGB><IOType>Standard</IOType></OSDiskConfiguration><DataDiskConfigurations/><ServiceName>PkrSrvnc5e26lzke</ServiceName><DeploymentName>PkrVMnc5e26lzke</DeploymentName><RoleName>PkrVMnc5e26lzke</RoleName><Location>West US</Location><CreatedTime>2015-04-25T07:16:03.3432256Z</CreatedTime><ModifiedTime>2015-04-25T07:16:03.3432256Z</ModifiedTime><ImageFamily>PackerMade</ImageFamily><RecommendedVMSize>Small</RecommendedVMSize><IsPremium>false</IsPremium><VMImageState>VMImageReadyForUse</VMImageState><RoleStateOnCapture>StoppedVM</RoleStateOnCapture><RoleSizeOnCapture>Small</RoleSizeOnCapture></VMImage><VMImage><Name>PackerMade_OpenLogicImage_2015-April-25_19-40</Name><Label>PackerMade_OpenLogicImage</Label><Category>User</Category><Description>paker made image</Description><OSDiskConfiguration><Name>PackerMade_OpenLogicImage_2015-April-25_19-40-os-2015-04-26</Name><HostCaching>ReadWrite</HostCaching><OSState>Generalized</OSState><OS>Linux</OS><MediaLink>https://pmwus123.blob.core.windows.net/images/PackerMade_OpenLogicImage_2015-April-25_19-40-os-2015-04-26.vhd</MediaLink><LogicalDiskSizeInGB>30</LogicalDiskSizeInGB><IOType>Standard</IOType></OSDiskConfiguration><DataDiskConfigurations/><ServiceName>PkrSrv80big2920y</ServiceName><DeploymentName>PkrVM80big2920y</DeploymentName><RoleName>PkrVM80big2920y</RoleName><Location>West US</Location><CreatedTime>2015-04-26T02:45:46.8813467Z</CreatedTime><ModifiedTime>2015-04-26T02:45:46.8813467Z</ModifiedTime><ImageFamily>PackerMade</ImageFamily><RecommendedVMSize>Small</RecommendedVMSize><IsPremium>false</IsPremium><VMImageState>VMImageReadyForUse</VMImageState><RoleStateOnCapture>StoppedVM</RoleStateOnCapture><RoleSizeOnCapture>Small</RoleSizeOnCapture></VMImage><VMImage><Name>PackerMade_OpenLogicImage_2015-April-2_17-21</Name><Label>PackerMade_OpenLogicImage</Label><Category>User</Category><Description>paker made image</Description><OSDiskConfiguration><Name>PackerMade_OpenLogicImage_2015-April-2_17-21-os-2015-04-03</Name><HostCaching>ReadWrite</HostCaching><OSState>Generalized</OSState><OS>Linux</OS><MediaLink>https://pmwus123.blob.core.windows.net/images/PackerMade_OpenLogicImage_2015-April-2_17-21-os-2015-04-03.vhd</MediaLink><LogicalDiskSizeInGB>30</LogicalDiskSizeInGB><IOType>Standard</IOType></OSDiskConfiguration><DataDiskConfigurations/><ServiceName>PkrSrvtnpnhpozbd</ServiceName><DeploymentName>PkrVMtnpnhpozbd</DeploymentName><RoleName>PkrVMtnpnhpozbd</RoleName><Location>West US</Location><CreatedTime>2015-04-03T00:51:27.2841004Z</CreatedTime><ModifiedTime>2015-04-03T00:51:27.2841004Z</ModifiedTime><ImageFamily>PackerMade</ImageFamily><RecommendedVMSize>Small</RecommendedVMSize><IsPremium>false</IsPremium><VMImageState>VMImageReadyForUse</VMImageState><RoleStateOnCapture>StoppedVM</RoleStateOnCapture><RoleSizeOnCapture>Small</RoleSizeOnCapture></VMImage><VMImage><Name>PackerMade_OpenLogicImage_2015-April-2_18-2</Name><Label>PackerMade_OpenLogicImage</Label><Category>User</Category><Description>paker made image</Description><OSDiskConfiguration><Name>PackerMade_OpenLogicImage_2015-April-2_18-2-os-2015-04-03</Name><HostCaching>ReadWrite</HostCaching><OSState>Generalized</OSState><OS>Linux</OS><MediaLink>https://pmwus123.blob.core.windows.net/images/PackerMade_OpenLogicImage_2015-April-2_18-2-os-2015-04-03.vhd</MediaLink><LogicalDiskSizeInGB>30</LogicalDiskSizeInGB><IOType>Standard</IOType></OSDiskConfiguration><DataDiskConfigurations/><ServiceName>PkrSrv24voud9zhz</ServiceName><DeploymentName>PkrVM24voud9zhz</DeploymentName><RoleName>PkrVM24voud9zhz</RoleName><Location>West US</Location><CreatedTime>2015-04-03T01:32:55.6802049Z</CreatedTime><ModifiedTime>2015-04-03T01:32:55.6802049Z</ModifiedTime><ImageFamily>PackerMade</ImageFamily><RecommendedVMSize>Small</RecommendedVMSize><IsPremium>false</IsPremium><VMImageState>VMImageReadyForUse</VMImageState><RoleStateOnCapture>StoppedVM</RoleStateOnCapture><RoleSizeOnCapture>Small</RoleSizeOnCapture></VMImage><VMImage><Name>PackerMade_OpenLogicImage_2015-April-3_10-54</Name><Label>PackerMade_OpenLogicImage</Label><Category>User</Category><Description>paker made image</Description><OSDiskConfiguration><Name>PackerMade_OpenLogicImage_2015-April-3_10-54-os-2015-04-03</Name><HostCaching>ReadWrite</HostCaching><OSState>Generalized</OSState><OS>Linux</OS><MediaLink>https://pmwus123.blob.core.windows.net/images/P...
        integration_test.go:320: Selecting image 'fb83b3509582419d99629ce476bcb5c8__SQL-Server-2014-RTM-12.0.2430.0-OLTP-ENU-Win2012R2-cy14su11'
        managementclient.go:79: AZURE: POST services/hostedservices
        managementclient.go:81:    >>> <CreateHostedService xmlns="http://schemas.microsoft.com/windowsazure"><ServiceName>sdk4cv1aadeyjs0</ServiceName><Label>c2RrNGN2MWFhZGV5anMw</Label><Description></Description><Location>South Central US</Location></CreateHostedService>
        managementclient.go:86:    <<< OperationID: a148ce88768ea25b9ff184c4f880b723
        managementclient.go:79: AZURE: POST services/hostedservices/sdk4cv1aadeyjs0/deployments
        managementclient.go:81:    >>> <Deployment xmlns="http://schemas.microsoft.com/windowsazure"><Name>sdk4cv1aadeyjs0</Name><DeploymentSlot>Production</DeploymentSlot><Label>sdk4cv1aadeyjs0</Label><RoleList><Role><RoleName>sdk4cv1aadeyjs0</RoleName><RoleType>PersistentVMRole</RoleType><ConfigurationSets><ConfigurationSet><ConfigurationSetType>WindowsProvisioningConfiguration</ConfigurationSetType><ComputerName>sdk4cv1aadeyjs0</ComputerName><AdminPassword>cdtbdurphrtjlEFEXMSQCDTBDURPHRTJL32165337402830006484efexms</AdminPassword><EnableAutomaticUpdates>true</EnableAutomaticUpdates><StoredCertificateSettings></StoredCertificateSettings><AdminUsername>azureuser</AdminUsername><InputEndpoints></InputEndpoints><SubnetNames></SubnetNames><PublicIPs></PublicIPs></ConfigurationSet><ConfigurationSet><ConfigurationSetType>NetworkConfiguration</ConfigurationSetType><StoredCertificateSettings></StoredCertificateSettings><InputEndpoints><InputEndpoint><LocalPort>22</LocalPort><Name>SSH</Name><Port>22</Port><Protocol>TCP</Protocol></InputEndpoint></InputEndpoints><SubnetNames></SubnetNames><PublicIPs></PublicIPs></ConfigurationSet></ConfigurationSets><ResourceExtensionReferences></ResourceExtensionReferences><VMImageName>fb83b3509582419d99629ce476bcb5c8__SQL-Server-2014-RTM-12.0.2430.0-OLTP-ENU-Win2012R2-cy14su11</VMImageName><MediaLocation>http://portalvhdsw6j5mnbx6qmy.blob.core.windows.net/sdk4cv1aadeyjs0</MediaLocation><DataVirtualHardDisks></DataVirtualHardDisks><RoleSize>Standard_D4</RoleSize></Role></RoleList><Dns><DnsServers></DnsServers></Dns><LoadBalancers></LoadBalancers></Deployment>
        managementclient.go:84:    <<< ERROR: Error response from Azure. Code: BadRequest, Message: In order to use extension reference, ProvisionGuestAgent must be set during virtual machine provisioning.
        integration_test.go:192: Error response from Azure. Code: BadRequest, Message: In order to use extension reference, ProvisionGuestAgent must be set during virtual machine provisioning.
        integration_test.go:197: Deleting hosted service: sdk4cv1aadeyjs0
        managementclient.go:79: AZURE: DELETE services/hostedservices/sdk4cv1aadeyjs0?comp=media
        managementclient.go:86:    <<< OperationID: 0d68e388b0f6a7c6b0d194a3f161785d
FAIL
```

**Comment by paulmey** [comment]
This may be because of the empty ResourceExtensionReferences element, I'll investigate...

**Comment by paulmey** [comment]
Yep... if I rename the XML element the test succeeds... This was introduced by https://github.com/Azure/azure-sdk-for-go/pull/120/files#diff-1fa4f35573c334c3564b4beebfd085eeL228

I'll see if I can fix it without introducing pointers... :-) @svanharmelen @ahmetalpbalkan

**Comment by svanharmelen** [comment]
@paulmey hmm... Nasty... So maybe we need a custom xml marshal func after all.

**Comment by paulmey** [comment]
That, or maybe just a second level there...

**Comment by paulmey** [comment]
@svanharmelen in this particular case, I think it makes sense to distinguish between an empty array of 'resource extension references' and no array at all (nil). Especially in the case of an 'Update Role' operation.
An empty array means that you want to remove all extensions, whereas no array (nil) means that you do not wish to update this aspect of the Role.
Let me test out with some integration tests whether this is the way it works...

**Comment by paulmey** [comment]
After doing some hands on tests (paulmey@c7b4d1d), it appears that for `UpdateRole`, nil and empty array are semantically equivalent (ie. I was wrong above). Extensions are deleted by updating the status to `uninstall`.

**Comment by ahmetalpbalkan** [comment]
@paulmey wow interesting.

**Comment by paulmey** [comment]
well... that's an upbeat reaction... :wink:

**Comment by paulmey** [comment]
fixed by #165
