### PR TITLE
Minor release v40.6.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
> Hold on, looks like `apimanagement` is broken. Needs to be rebuilt with the latest generator.
> 
> ```
> # github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-12-01/apimanagement
> services/apimanagement/mgmt/2019-12-01/apimanagement/userconfirmationpassword.go:119:2: cannot use autorest.Response value as type *http.Response in return argument
> services/apimanagement/mgmt/2019-12-01/apimanagement/userconfirmationpassword.go:119:20: not enough arguments in call to client.Send
> 	have (*http.Request, autorest.SendDecorator)
> 	want (context.Context, string, string, string)
> ```

Oops, I will take it a look

**Comment by ArcturusZhang** [comment]
The failure should be fixed in #8018
